steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull eu.gcr.io/$PROJECT_ID/http-gallery-beego:latest || exit 0
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'eu.gcr.io/$PROJECT_ID/http-gallery-beego:$COMMIT_SHA',
    '--cache-from', 'eu.gcr.io/$PROJECT_ID/http-gallery-beego:latest',
    '.'
  ]
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/http-gallery-beego:$COMMIT_SHA']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'http-gallery-beego'
  - '--image'
  - 'eu.gcr.io/$PROJECT_ID/http-gallery-beego:$COMMIT_SHA'
  - '--region'
  - 'europe-west1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--cpu'
  - '1'
  - '--memory'
  - '128Mi'
  - '--max-instances'
  - '2'
images:
- eu.gcr.io/$PROJECT_ID/http-gallery-beego